<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>MesIngest.Watch.FluentPrototype</RootNamespace>
    <AssemblyName>MesIngest.Watch.FluentPrototype</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="WPF-UI" />
  </ItemGroup>

</Project>
