<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MesIngest.Core\MesIngest.Core.csproj" />
    <ProjectReference Include="..\MesIngest.Infrastructure\MesIngest.Infrastructure.csproj" />
  </ItemGroup>

</Project>
