<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>MesIngest.Tests</_Parameter1>
    </AssemblyAttribute>
    <PackageReference Include="Microsoft.Data.SqlClient" />
    <PackageReference Include="Oracle.ManagedDataAccess.Core" />
    <PackageReference Include="System.Data.Odbc" />
  </ItemGroup>

</Project>
