<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>MesIngest.Watch.Prototype</RootNamespace>
    <AssemblyName>MesIngest.Watch.Prototype</AssemblyName>
  </PropertyGroup>

</Project>
